### ISSUE TITLE
Missing error mapper crashes an app

### ISSUE THREAD

**Issue by tpluscode** [PDMLab/express-http-problem-details#12]
I just bumped into a problem that when a mapper is not registered, the handler will break and express dies.

The problem is scattered across multiple places. In this end, the mapping strategy is inhonest about the return value from `map`. The typing says that it will be a `ProblemDocument` yet an `undefined` is also possible.

https://github.com/PDMLab/express-http-problem-details/blob/master/src/ExpressMappingStrategy.ts#L16

I suggest `strict: true` in `tsconfig.json` to prevent such subtle errors.

---

Second, it actually falls to the registry that it does not find a mapper even when the default mapper is used.

I propose to always return the default mapper when a more specific cannot be found. I think it could also be possible to walk up the prototype chain to sort of emulate polymorphism.

**Comment by AlexZeitler** [comment]
> I suggest strict: true in tsconfig.json to prevent such subtle errors.

Makes sense. Do you want to send a PR?

> I propose to always return the default mapper when a more specific cannot be found.

This might make sense. I wonder if we should give a hint that the default mapper has been used. Sort of an `debug` message or something.

> I think it could also be possible to walk up the prototype chain to sort of emulate polymorphism.

I think `instanceof` might work here as well as a first implementation.

**Comment by tpluscode** [comment]
> This might make sense. I wonder if we should give a hint that the default mapper has been used. 

I would say rather not?

> I think instanceof might work here as well as a first implementation.

Of course, let me do that instead of the string comparison!

**Comment by AlexZeitler** [comment]
> 
> I would say rather not?
> 

ok

> 
> Of course, let me do that instead of the string comparison!

ok
