### ISSUE TITLE
Does ExpressMappingStrategy belong here?

### ISSUE THREAD

**Issue by tpluscode** [PDMLab/express-http-problem-details#15]
I'm not sure how specific the `ExpressMappingStrategy` is to express actually? 

I think right now that maybe it belongs to the `http-problem-details-mapper` package.

**Comment by AlexZeitler** [comment]
Currently it does not tied to `express`.

It is same as the `HapiMappingStrategy` [here](https://github.com/PDMLab/hapi-http-problem-details/blob/master/src/HapiMappingStrategy.ts).

And even if someone would have the need to make it depend on `express` related stuff, it would still be possible by implementing a custom `IMappingStrategy`.

**Comment by tpluscode** [comment]
My point was only that maybe the default implementation could be moved to the upstream packages. Just a thought

**Comment by AlexZeitler** [comment]
Yes, I understood it that way and I wanted to express I agree with that 😄

**Comment by AlexZeitler** [comment]
Do you want to send a PR here or should I do it?

Would you mind reviewing the PRs then?

I would suggest it should be named `DefaultMappingStrategy` as abstract class [`MappingStrategy`](https://github.com/PDMLab/http-problem-details-mapper/blob/master/src/IMappingStrategy.ts) already exists in `http-problem-details-mapper`.

**Comment by tpluscode** [comment]
👍 to the name but I would also move the implementation to the `mapper` package.

**Comment by AlexZeitler** [comment]
Yes, from my understanding we already have committed to move it to the mapper package.

**Comment by tpluscode** [comment]
Right, right. This is not a high priority for me right now. Go ahead and I will gladly review. Otherwise maybe can try over the weekend.

**Comment by AlexZeitler** [comment]
No worries, I can do it. I just wanted to avoid misunderstandings.

**Comment by AlexZeitler** [comment]
This is the PR for `http-problem-details-mapper`: 
https://github.com/PDMLab/http-problem-details-mapper/pull/14
