### ISSUE TITLE
Slack invite

### ISSUE THREAD

**Issue by tpluscode** [PDMLab/express-http-problem-details#16]
By the way, I wanted to join your Slack but the invitation link expired.

That said, maybe it's more hassle-free to set up a gitter community? It is more readily accessible to GitHub users than yet another Slack channel.

**Comment by AlexZeitler** [comment]
Thanks for letting me know about the broken link. You should have received an invite to https://gitter.im/pdmlab

**Comment by KenEucker** [comment]
@AlexZeitler is the slack no more? It appears that there's no one around on the gitter?

I was hoping to discuss an issue I was having trying to use compose.down.

**Comment by AlexZeitler** [comment]
@KenEucker Somehow I lost my notifications from gitter. Feel free to post your issue on gitter.

**Comment by KenEucker** [comment]
@AlexZeitler I posted on Gitter and tagged you. Sorry again for using this image to reach out.
