### ISSUE TITLE
Request to use Response.json over Response.send(JSON.stringify...)

### ISSUE THREAD

**Issue by mastermatt** [PDMLab/express-http-problem-details#23]
I'm curious if decision to use `.send` instead of `.json` was intentional for some reason:
https://github.com/PDMLab/express-http-problem-details/blob/1da9af2797366eb18375e9c3e3e65823af6c3902/src/HttpProblemResponse.ts#L30

The issue being, Expresses `Response.json` use [app settings](https://expressjs.com/en/4x/api.html#app.set) for the replacer, escape, and spaces settings of JSON.stringify and stringifying the payload directly bypasses these options. 

If it doesn't make a difference to the functionality of this lib, I'd be happy to open a PR.

**Comment by AlexZeitler** [comment]
@mastermatt Thanks for pointing this out. From my perspective, it has not been chosen by intent so using `.json()` should be ok.

Any thoughts on this @tpluscode?

**Comment by tpluscode** [comment]
No objections here 👌
